# Generated by Django 3.1.7 on 2021-04-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=255, verbose_name='Profissão')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Rede Social')),
                ('urlPrincipal', models.CharField(max_length=255, verbose_name='URL Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTelefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocialCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, verbose_name='Username')),
                ('redeSocial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.redesocial', verbose_name='Rede Social##')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('dataCadastroProduto', models.DateTimeField(auto_now_add=True)),
                ('categoriaProdutoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.categoriaproduto')),
                ('marcaId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome funcionario')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_contratacao', models.DateField(verbose_name='Data da contratação')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
                ('bool_habilitacao', models.BooleanField(verbose_name='Possui habilitação')),
                ('usuario', models.CharField(max_length=255, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=8, verbose_name='Senha')),
                ('cargoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.cargo', verbose_name='Cargo')),
                ('setorId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.setor', verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_nascimento', models.DateField()),
                ('telefoneCliente', models.CharField(max_length=11, verbose_name='Telefone')),
                ('sexoId', models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='loja.sexo', verbose_name='Sexo')),
                ('username', models.CharField(default='', max_length=120, verbose_name='Perfil')),
                ('boolSegueALoja', models.BooleanField(default=False, verbose_name='Segue a loja?')),
                ('profissaoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.profissao', verbose_name='Profissao')),
                ('redeSocial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loja.redesocial', verbose_name='Rede social')),
            ],
        ),
    ]
